apiVersion: newdeploymentv1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: volume1
          secret:
            secretName: test-secret
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
          env:
            - name: greeting
              value: "hello"

          volumeMounts:
            - name: volume1
              mountPath: "/etc/volume1"
              readOnly: true
